// <auto-generated />
using System;
using GarageManagementSoftware.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GarageManagementSoftware.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GarageManagementSoftware.Models.ENITTY.Common.UnitModel", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("create_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("delete_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("delete_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("id")
                        .HasColumnType("int");

                    b.Property<bool?>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("is_delete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("code");

                    b.ToTable("Unit", (string)null);
                });

            modelBuilder.Entity("GarageManagementSoftware.Models.ENITTY.DataSystem.AccountModel", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("create_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("delete_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("delete_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("id")
                        .HasColumnType("int");

                    b.Property<bool?>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("is_delete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("code");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("GarageManagementSoftware.Models.ENITTY.DataSystem.CompanyModel", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("create_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("delete_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("delete_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("id")
                        .HasColumnType("int");

                    b.Property<bool?>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("is_delete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("code");

                    b.ToTable("Company", (string)null);
                });

            modelBuilder.Entity("GarageManagementSoftware.Models.ENITTY.DataSystem.PermissionModel", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("create_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("delete_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("delete_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("id")
                        .HasColumnType("int");

                    b.Property<bool?>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("is_delete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("code");

                    b.ToTable("Permission", (string)null);
                });

            modelBuilder.Entity("GarageManagementSoftware.Models.ENITTY.DataSystem.UserModel", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("birthday")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("delete_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("delete_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("id")
                        .HasColumnType("int");

                    b.Property<bool?>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("is_delete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("code");

                    b.ToTable("User", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("GarageManagementSoftware.Models.ENITTY.Function.Employee.DepartmentModel", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("create_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("delete_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("delete_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("id")
                        .HasColumnType("int");

                    b.Property<bool?>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("is_delete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("code");

                    b.ToTable("Department", (string)null);
                });

            modelBuilder.Entity("GarageManagementSoftware.Models.ENITTY.Function.Employee.EmployeeStatusModel", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("create_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("delete_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("delete_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("id")
                        .HasColumnType("int");

                    b.Property<bool?>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("is_delete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("code");

                    b.ToTable("EmployeeStatus", (string)null);
                });

            modelBuilder.Entity("GarageManagementSoftware.Models.ENITTY.Function.Employee.TypeEmployeeModel", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("create_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("delete_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("delete_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("id")
                        .HasColumnType("int");

                    b.Property<bool?>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("is_delete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("code");

                    b.ToTable("TypeEmployee", (string)null);
                });

            modelBuilder.Entity("GarageManagementSoftware.Models.ENITTY.Function.GarageAccess.AccessModel", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("company_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("company_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("delete_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("delete_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("id")
                        .HasColumnType("int");

                    b.Property<string>("inventory_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inventory_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("is_delete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("price_sell")
                        .HasColumnType("float");

                    b.Property<double?>("prive_buy")
                        .HasColumnType("float");

                    b.Property<double?>("tax_percent")
                        .HasColumnType("float");

                    b.Property<DateTime?>("update_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("code");

                    b.ToTable("Access", (string)null);
                });

            modelBuilder.Entity("GarageManagementSoftware.Models.ENITTY.Function.GarageAccess.InventoryModel", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("company_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("company_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("delete_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("delete_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("id")
                        .HasColumnType("int");

                    b.Property<bool?>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("is_delete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("code");

                    b.ToTable("Inventory", (string)null);
                });

            modelBuilder.Entity("GarageManagementSoftware.Models.ENITTY.Function.Sale.HistoryReciveOtoModel", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("company_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("company_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customer_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customer_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("delete_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("delete_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employee_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employee_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("id")
                        .HasColumnType("int");

                    b.Property<bool?>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("is_delete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("code");

                    b.ToTable("HistoryReciveOto", (string)null);
                });

            modelBuilder.Entity("GarageManagementSoftware.Models.ENITTY.Function.Sale.PaymentVoucherDetailModel", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("access_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("company_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("company_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("delete_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("delete_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("discount")
                        .HasColumnType("float");

                    b.Property<int?>("id")
                        .HasColumnType("int");

                    b.Property<bool?>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("is_delete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("paymentVoucher_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("price")
                        .HasColumnType("float");

                    b.Property<double?>("price_total")
                        .HasColumnType("float");

                    b.Property<double?>("tax_percent")
                        .HasColumnType("float");

                    b.Property<double?>("tax_price")
                        .HasColumnType("float");

                    b.Property<DateTime?>("update_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("code");

                    b.ToTable("PaymentVoucherDetail", (string)null);
                });

            modelBuilder.Entity("GarageManagementSoftware.Models.ENITTY.Function.Sale.PaymentVoucherModel", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("company_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("company_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("delete_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("delete_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("discount")
                        .HasColumnType("float");

                    b.Property<string>("historyReviceOto_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("historyReviceOtocode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("id")
                        .HasColumnType("int");

                    b.Property<bool?>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("is_delete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("is_payment")
                        .HasColumnType("bit");

                    b.Property<bool?>("is_quote")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("payment_change")
                        .HasColumnType("float");

                    b.Property<double?>("payment_received")
                        .HasColumnType("float");

                    b.Property<double?>("payment_total")
                        .HasColumnType("float");

                    b.Property<double?>("price")
                        .HasColumnType("float");

                    b.Property<double?>("price_total")
                        .HasColumnType("float");

                    b.Property<double?>("print_count")
                        .HasColumnType("float");

                    b.Property<double?>("tax_percent")
                        .HasColumnType("float");

                    b.Property<double?>("tax_price")
                        .HasColumnType("float");

                    b.Property<DateTime?>("update_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("code");

                    b.HasIndex("historyReviceOtocode");

                    b.ToTable("PaymentVoucher", (string)null);
                });

            modelBuilder.Entity("GarageManagementSoftware.Models.ENITTY.Function.Sale.RecieptVoucherDetailModel", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("access_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("company_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("company_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("delete_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("delete_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("discount")
                        .HasColumnType("float");

                    b.Property<int?>("id")
                        .HasColumnType("int");

                    b.Property<bool?>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("is_delete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("price")
                        .HasColumnType("float");

                    b.Property<double?>("price_total")
                        .HasColumnType("float");

                    b.Property<string>("recieptVoucher_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("tax_percent")
                        .HasColumnType("float");

                    b.Property<double?>("tax_price")
                        .HasColumnType("float");

                    b.Property<DateTime?>("update_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("code");

                    b.ToTable("RecieptVoucherDetail", (string)null);
                });

            modelBuilder.Entity("GarageManagementSoftware.Models.ENITTY.Function.Sale.RecieptVoucherModel", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("company_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("company_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("delete_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("delete_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("discount")
                        .HasColumnType("float");

                    b.Property<string>("historyReviceOto_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("historyReviceOtocode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("id")
                        .HasColumnType("int");

                    b.Property<string>("inventory_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inventory_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("is_delete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("is_payment")
                        .HasColumnType("bit");

                    b.Property<bool?>("is_quote")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("payment_change")
                        .HasColumnType("float");

                    b.Property<double?>("payment_received")
                        .HasColumnType("float");

                    b.Property<double?>("payment_total")
                        .HasColumnType("float");

                    b.Property<double?>("price")
                        .HasColumnType("float");

                    b.Property<double?>("price_total")
                        .HasColumnType("float");

                    b.Property<double?>("tax_percent")
                        .HasColumnType("float");

                    b.Property<double?>("tax_price")
                        .HasColumnType("float");

                    b.Property<DateTime?>("update_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("code");

                    b.HasIndex("historyReviceOtocode");

                    b.ToTable("RecieptVoucher", (string)null);
                });

            modelBuilder.Entity("GarageManagementSoftware.Models.ENITTY.Function.WorkFlow.ProjectModel", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("company_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("company_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("delete_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("delete_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("id")
                        .HasColumnType("int");

                    b.Property<bool?>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("is_delete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("code");

                    b.ToTable("Project", (string)null);
                });

            modelBuilder.Entity("GarageManagementSoftware.Models.ENITTY.Function.WorkFlow.TaskModel", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("company_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("company_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("delete_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("delete_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employee_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("id")
                        .HasColumnType("int");

                    b.Property<bool?>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("is_delete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("project_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("project_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("code");

                    b.ToTable("Task", (string)null);
                });

            modelBuilder.Entity("GarageManagementSoftware.Models.ENITTY.Function.WorkFlow.WorkFlowStatusModel", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("create_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("delete_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("delete_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("id")
                        .HasColumnType("int");

                    b.Property<bool?>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("is_delete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("code");

                    b.ToTable("WorkFlowStatus", (string)null);
                });

            modelBuilder.Entity("GarageManagementSoftware.Models.ENITTY.Function.WorkFlow.WorkFlowTypeModel", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("create_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("delete_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("delete_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("id")
                        .HasColumnType("int");

                    b.Property<bool?>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("is_delete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("code");

                    b.ToTable("WorkFlowType", (string)null);
                });

            modelBuilder.Entity("GarageManagementSoftware.Models.ENITTY.Function.Employee.EmployeeModel", b =>
                {
                    b.HasBaseType("GarageManagementSoftware.Models.ENITTY.DataSystem.UserModel");

                    b.Property<string>("company_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("company_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("is_customer")
                        .HasColumnType("bit");

                    b.Property<bool?>("is_employee")
                        .HasColumnType("bit");

                    b.Property<bool?>("is_supply")
                        .HasColumnType("bit");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("GarageManagementSoftware.Models.ENITTY.Function.Sale.PaymentVoucherModel", b =>
                {
                    b.HasOne("GarageManagementSoftware.Models.ENITTY.Function.Sale.HistoryReciveOtoModel", "historyReviceOto")
                        .WithMany()
                        .HasForeignKey("historyReviceOtocode");

                    b.Navigation("historyReviceOto");
                });

            modelBuilder.Entity("GarageManagementSoftware.Models.ENITTY.Function.Sale.RecieptVoucherModel", b =>
                {
                    b.HasOne("GarageManagementSoftware.Models.ENITTY.Function.Sale.HistoryReciveOtoModel", "historyReviceOto")
                        .WithMany()
                        .HasForeignKey("historyReviceOtocode");

                    b.Navigation("historyReviceOto");
                });

            modelBuilder.Entity("GarageManagementSoftware.Models.ENITTY.Function.Employee.EmployeeModel", b =>
                {
                    b.HasOne("GarageManagementSoftware.Models.ENITTY.DataSystem.UserModel", null)
                        .WithOne()
                        .HasForeignKey("GarageManagementSoftware.Models.ENITTY.Function.Employee.EmployeeModel", "code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
